smb_admin_user: glomyer
smb_admin_group: nas_admins

# Unique domain groups across all volumes’ smb_shares
smb_domain_groups: >-
  {{
    smb_volumes
    | map(attribute='smb_shares')
    | list
    | flatten
    | map(attribute='domain_group')
    | list
    | unique
  }}

smb_volumes:
  - storage_uuid: "257d85bc-003d-46df-8405-0e6135a0c94f"
    smb_volume_root_path: /mnt/storage
    smb_volume_root_share: storage
    smb_shares:
      # For users
      - name: container
        path: /mnt/container/
        service_user: files
        service_password: "{{ vault_nas_shared_files_password }}"
        domain_group: media_container_rw
        read_only: false

      - name: files
        path: /mnt/storage/shared/files
        service_user: files
        service_password: "{{ vault_nas_shared_files_password }}"
        domain_group: media_shared_files_rw
        read_only: false

      # For applications
      - name: music
        path: /mnt/storage/music
        service_user: navidrome
        service_password: "{{ vault_nas_navidrome_password }}"
        domain_group: media_music_ro
        read_only: true

      - name: videos
        path: /mnt/storage/videos
        service_user: jellyfin
        service_password: "{{ vault_nas_jellyfin_password }}"
        domain_group: media_videos_ro
        read_only: true

      - name: metube
        path: /mnt/storage/shared/metube
        service_user: metube
        service_password: "{{ vault_nas_metube_password }}"
        domain_group: media_shared_metube_rw
        read_only: false


  - storage_uuid: "c16635fb-1b15-4049-a24f-90e8eeaed060"
    smb_volume_root_path: /mnt/backup
    smb_volume_root_share: backup
    smb_shares:
      - name: proxmox
        path: /mnt/backup/proxmox
        service_user: proxmox
        service_password: "{{ vault_smb_proxmox_password }}"
        domain_group: media_shared_proxmox_rw
        read_only: false
