- name: Run Glances container
  community.docker.docker_container:
    name: "{{ glances_container_name }}"
    image: "{{ glances_image }}"
    state: started
    restart_policy: always
    command: glances -w
    ports:
      - "{{ glances_web_port }}:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid_mode: host
    container_default_behavior: compatibility
