- name: Create Uptime Kuma volume
  community.docker.docker_volume:
    name: "{{ uptime_kuma_volume_name }}"

- name: Run Uptime Kuma container
  community.docker.docker_container:
    name: "{{ uptime_kuma_container_name }}"
    image: "{{ uptime_kuma_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ uptime_kuma_web_port }}:3001"
    volumes:
      - "{{ uptime_kuma_volume_name }}:/app/data"
    container_default_behavior: compatibility
    dns_servers:
      - "{{ main_host_ip }}"
