storage_uuid: "257d85bc-003d-46df-8405-0e6135a0c94f"
nas_root: /mnt/storage

nas_admin_user: glomyer
nas_admin_group: nas_admins
nas_storage_share: storage

# Domain groups
nas_domain_groups: "{{ nas_shares | map(attribute='domain_group') | list | unique }}"

nas_shares:
  - name: music
    path: "{{ nas_root }}/music"
    service_user: navidrome
    service_password: "{{ vault_nas_navidrome_password }}"
    domain_group: media_music_ro
    read_only: true

  - name: videos
    path: "{{ nas_root }}/videos"
    service_user: jellyfin
    service_password: "{{ vault_nas_jellyfin_password }}"
    domain_group: media_videos_ro
    read_only: true
  
  - name: metube
    path: "{{ nas_root }}/shared/metube"
    service_user: metube
    service_password: "{{ vault_nas_metube_password }}"
    domain_group: media_shared_metube_rw
    read_only: false
