- name: Extract system metadata
  hosts: [RaspberryPi, ServicesHost]
  become: true
  vars:
    application_tags:
      - caddy
      - docker
      - golang
      - olivetin
  roles:
    - role: extract_metadata
      tags: "{{ application_tags }}"

- name: Install host applications
  hosts: [RaspberryPi, ServicesHost]
  become: true
  vars:
    caddy_caddyfiles:
      RaspberryPi: edge.Caddyfile.j2
      ServicesHost: services.Caddyfile.j2
  roles:
    - role: services/docker
      tags: docker

    - role: services/golang
      tags: golang

    - role: services/caddy
      tags: caddy
      caddyfile: "{{ caddy_caddyfiles[group_names|first] }}"

    - role: services/olivetin
      tags: olivetin
      when: "'RaspberryPi' in group_names"
