- name: Configure NAS
  hosts: [NasHost]
  become: true
  roles:
    - role: configure_smb
      tags: configure_smb

- name: Configure SMB Share mounts
  hosts: [ServicesHost]
  become: true
  roles:
    - role: client_smb_mounts
      tags: client_smb_mounts
