- name: Extract system metadata
  hosts: [ServicesHost, RaspberryPi]
  become: true
  vars:
    container_tags:
      - adguard_home
      - dashy
      - diun
      - file_browser
      - freshrss
      - glances
      - jellyfin
      - metube
      - navidrome
      - portainer
      - stirling_pdf
      - uptime_kuma
      - vaultwarden
      - vikunja
  roles:
    - role: extract_metadata
      tags: "{{ container_tags }}"

- name: Set up containerized services
  hosts: [ServicesHost, RaspberryPi]
  roles:
    - role: containers/dashy
      tags: dashy
      when: "'ServicesHost' in group_names"

    - role: containers/diun
      tags: diun

    - role: containers/freshrss
      tags: freshrss
      when: "'ServicesHost' in group_names"

    - role: containers/glances
      tags: glances

    - role: containers/jellyfin
      tags: jellyfin
      when: "'ServicesHost' in group_names"

    - role: containers/metube
      tags: metube
      when: "'ServicesHost' in group_names"

    - role: containers/navidrome
      tags: navidrome
      when: "'ServicesHost' in group_names"

    - role: containers/portainer
      tags: portainer
      when: "'ServicesHost' in group_names"

    - role: containers/stirling_pdf
      tags: stirling_pdf
      when: "'ServicesHost' in group_names"

    - role: containers/uptime_kuma
      tags: uptime_kuma
      when: "'ServicesHost' in group_names"

    - role: containers/vaultwarden
      tags: vaultwarden
      when: "'ServicesHost' in group_names"

    - role: containers/vikunja
      tags: vikunja
      when: "'ServicesHost' in group_names"

    - role: containers/adguard_home
      tags: adguard_home
      when: "'RaspberryPi' in group_names"

    - role: containers/file_browser
      tags: file_browser
      when: "'RaspberryPi' in group_names"

    # - role: containers/pihole
    #   tags: pihole


- name: Remove unused resources
  hosts: [ServicesHost, RaspberryPi]
  tasks:
    - name: Prune unused Docker images
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: false
          until: 24h
