- name: Upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"

- name: Install required packages
  ansible.builtin.apt:
    name: [
      'apt-transport-https',
      'ca-certificates',
      'curl',
      'gnupg',
      'python3-docker',
      'python3-pip',
      'python3-setuptools',
      'argon2',
    ]
    state: present
