- name: Create config directory for AdGuard Home
  become: true
  ansible.builtin.file:
    path: "{{ adguard_home_conf_dir }}"
    state: directory
    mode: '0755'

- name: Create work directory for AdGuard Home
  become: true
  ansible.builtin.file:
    path: "{{ adguard_home_work_dir }}"
    state: directory
    mode: '0755'

- name: Run AdGuard Home container
  community.docker.docker_container:
    name: "{{ adguard_home_container_name }}"
    image: "{{ adguard_home_image }}"
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ adguard_home_work_dir }}:/opt/adguardhome/work"
      - "{{ adguard_home_conf_dir }}:/opt/adguardhome/conf"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      # - "80:80/tcp"
      # - "443:443/tcp"
      # - "443:443/udp"
      - "{{ adguard_home_web_port }}:3000/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    container_default_behavior: compatibility
