caddy_version: "2.10.0"
caddy_download_url: "https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_arm64.tar.gz"
caddy_bin_path: "/usr/local/bin/caddy"
caddy_config_path: "/etc/caddy/Caddyfile"
caddy_data_dir: "/var/lib/caddy"
