- name: Deploy Portainer
  hosts: servers
  become: true

  tasks:
    - name: Create Portainer volume
      community.docker.docker_volume:
        name: portainer_data

    - name: Run Portainer container
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        container_default_behavior: compatibility
        ports:
          - "8000:8000" # Edge Agent
          - "9443:9443" # Web UI
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

- name: Deploy Uptime Kuma
  hosts: servers
  become: true
  vars:
    uptime_kuma_volume: uptime-kuma

  tasks:
    - name: Create Uptime Kuma volume
      community.docker.docker_volume:
        name: "{{ uptime_kuma_volume }}"

    - name: Run Uptime Kuma container
      community.docker.docker_container:
        name: uptime-kuma
        image: louislam/uptime-kuma:1
        state: started
        restart_policy: always
        ports:
          - "3001:3001"
        volumes:
          - "{{ uptime_kuma_volume }}:/app/data"
        container_default_behavior: compatibility

- name: Deploy Glances
  hosts: servers
  become: true

  tasks:
    - name: Run Glances container
      community.docker.docker_container:
        name: glances
        image: nicolargo/glances:latest-full
        state: started
        restart_policy: always
        command: glances -w
        ports:
          - "61208:61208"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        pid_mode: host
        container_default_behavior: compatibility
