- name: Set up system
  hosts: servers
  become: true
  roles:
    - role: common
      tags: common

    - role: olivetin
      tags: olivetin

    - role: caddy
      tags: caddy

- name: Set up containerized services
  hosts: servers
  roles:
    - role: dashy
      tags: dashy

    # - role: pihole
    #   tags: pihole

    - role: adguard_home
      tags: adguard_home

    - role: glances
      tags: glances

    - role: portainer
      tags: portainer

    - role: uptime_kuma
      tags: uptime_kuma

    - role: metube
      tags: metube
