- name: Deploy Pi-hole container
  hosts: servers
  become: true

  tasks:
    - name: Create Pi-hole config volume
      community.docker.docker_volume:
        name: pihole_etc

    - name: Run Pi-hole container
      community.docker.docker_container:
        name: pihole
        image: pihole/pihole:2025.06.2
        state: started
        restart_policy: always
        container_default_behavior: compatibility
        network_mode: host
        env:
          TZ: "America/Manaus"
          FTLCONF_webserver_api_password: "test"
          FTLCONF_dns_upstreams: 127.0.0.1#5335
          # FTLCONF_dns_upstreams: "1.1.1.1;1.0.0.1" # Cloudflare DNS
        volumes:
          - /opt/pihole:/etc/pihole
        capabilities:
          - NET_ADMIN
          # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
          # - SYS_TIME
          # Optional, if Pi-hole should get some more processing time
          # - SYS_NICE


- name: Deploy Unbound DNS server
  hosts: servers
  become: true
  vars:
    unbound_port: 5335

  tasks:
    - name: Run Unbound container
      community.docker.docker_container:
        name: unbound
        image: mvance/unbound-rpi:1.22.0
        state: started
        restart_policy: always
        ports:
          - "{{ unbound_port }}:53/udp"
          - "{{ unbound_port }}:53/tcp"
        container_default_behavior: compatibility
