- name: Run Unbound container
  community.docker.docker_container:
    name: "{{ pihole_unbound_container_name }}"
    image: "{{ pihole_unbound_image }}"
    state: stopped
    restart_policy: always
    ports:
      - "{{ pihole_unbound_port }}:53/udp"
      - "{{ pihole_unbound_port }}:53/tcp"
    container_default_behavior: compatibility
